### ISSUE TITLE
Gorgeous, but some seem to be lacking consistency

### ISSUE THREAD

**Issue by proimage** [CoreyGinnivan/system-uicons#11]
First of all, these are gorgeous icons (I'd love to see them on icomoon!). Kudos!

This is definitely firmly in the realm of nitpicking, but I did notice a few specific icons that seemed inconsistently drawn in relation to their counterparts:

- The Enter icons have a full doorway, but the Exit icons do not.
- The Fullscreen icon has four arrows; the Minimize icon uses chevrons instead.

There could be more; those were just the ones I noticed while scrolling through the list on my phone. ;)

**Comment by CoreyGinnivan** [comment]
Thanks mate! Currently doing a sweep over little things like that, so I really appreciate the feedback. Will sort it out :)

**Comment by proimage** [comment]
Glad to be a help!

One more thing I noticed (in many icons packs, not just yours) is that many calendar icons don't obviously represent a calendar when they don't have the two binder rings sticking out from the top. ¯\_(ツ)_/¯

**Comment by CoreyGinnivan** [comment]
I've made a few tweaks in the latest batch, most of the things you specific were designed by choice. I'll come back to them if they continue to cause confusion by folks, thanks mate https://github.com/CoreyGinnivan/system-uicons/pull/28
