### ISSUE TITLE
Request: sun & moon icons

### ISSUE THREAD

**Issue by appel** [CoreyGinnivan/system-uicons#12]
These icons look stunning, thank you so much for making these available! I don't know if you take requests, but a sun & moon icon to indicate light and dark mode (like the ones on https://corey.ginnivan.net/) would be great!

**Comment by CoreyGinnivan** [comment]
Yep already made! Will be coming out in the next release with a tonne of others, stay tuned <3

**Comment by appel** [comment]
Thanks so much, excited for the next release!
