### ISSUE TITLE
Home icon is missing

### ISSUE THREAD

**Issue by midudev** [CoreyGinnivan/system-uicons#13]
Hi! First of all, awesome work! 🙇‍♂️ Thanks for sharing as it's very useful for my pet projects and I like a lot the style of the icons. :)

I saw that the preview image from Twitter is showing a Home icon but, while searching it in the catalogue, it seems that the Home icon is missing.

![image](https://user-images.githubusercontent.com/1561955/90260117-5c428c00-de4b-11ea-8566-ee04cdd9d1b7.png)

Could you please add it to the catalogue? Thanks!

**Comment by CoreyGinnivan** [comment]
Thanks mate, yep it'll be out in the next batch of icons. It does exist as you can see, honestly had no plans on which icons to release first, just went from top to bottom. Just in the process of cleaning things up

**Comment by CoreyGinnivan** [comment]
Added in the new batch https://github.com/CoreyGinnivan/system-uicons/pull/28
