### ISSUE TITLE
Next batch

### ISSUE THREAD

**Issue by hnnweb** [CoreyGinnivan/system-uicons#20]
When is the next batch coming?

In tickets from august, you are referencing this "Next batch"... Thats 4 months ago.

**Comment by CoreyGinnivan** [comment]
Hopefully only a few weeks out, just been a bit under the pump at the tail end of the year and needed break.

**Comment by CoreyGinnivan** [comment]
@hnnweb Next batch has been released, let me know if there's anything your particularly after https://github.com/CoreyGinnivan/system-uicons/pull/28
