### ISSUE TITLE
Something wrong with refresh.svg

### ISSUE THREAD

**Issue by bacebu4** [CoreyGinnivan/system-uicons#22]
Check the svg code of refresh icons. Something really gone wrong there. 
Here's the example of how it looks![image](https://user-images.githubusercontent.com/32079387/107211182-3ff86400-6a16-11eb-9415-338e5bae24e8.jpeg)

**Comment by CoreyGinnivan** [comment]
Working on a fix for some compression issues at the moment for this, was this when you tried to bring it into a design tool?

**Comment by bacebu4** [comment]
> Working on a fix for some compression issues at the moment for this, was this when you tried to bring it into a design tool?

That's happening when I'm downloading the icon and pasting it into figma
Though everything looks good when I open it in browser

**Comment by CoreyGinnivan** [comment]
Sweet thanks for the update. I'll see what I can do

**Comment by CoreyGinnivan** [comment]
Should be fixed in the latest PR https://github.com/CoreyGinnivan/system-uicons/pull/28
