### ISSUE TITLE
Community React library

### ISSUE THREAD

**Issue by mrtnzlml** [CoreyGinnivan/system-uicons#34]
Hi @CoreyGinnivan! 👋 Thanks for this amazing project! I've been having an eye on this project for a while and I finally got to work with it. It's a pleasure.

I noticed that there is an unfinished effort to create React components from one year ago (https://github.com/CoreyGinnivan/system-uicons/pull/3). I needed something finished and maintained though so I just created and published this: https://github.com/adeira/icons 😎 

```bash
yarn add @adeira/icons
```

The way how it's written, final goals, and thinking around this project are a bit different but I believe some people might find it useful. The question is, would you please consider mentioning this community project somewhere? I can send a PR.

BTW, I followed your steps and also released the library under ["The Unlicense" license](https://unlicense.org/). ❤️ 

Thanks for considering my question and thanks again for making this project available to the rest of the world.

**Comment by CoreyGinnivan** [comment]
Legend! This is awesome, nice one mate ❤️ I'll give it a shout out on Twitter 

P.S. (Sorry about the delay 😅)

**Comment by CoreyGinnivan** [comment]
Put a comment on the main GitHub page too, thanks again mate, looks great 👏

**Comment by mrtnzlml** [comment]
Awesome, thanks! 😊
