### ISSUE TITLE
Add more box icons

### ISSUE THREAD

**Issue by kmohrf** [CoreyGinnivan/system-uicons#40]
Hey,

there is a *Box* and *Box (Open)* icon already. I’d be nice to have

* [ ] a *Boxes* icon (like a little box pyramid)
* [ ] a *Box (Add)* icon (a box with a plus sign)

Thank you for your time :)

**Comment by CoreyGinnivan** [comment]
Ok no probs, can do!

**Comment by CoreyGinnivan** [comment]
@kmohrf Hey mate, do you have any examples of what you're after?

**Comment by kmohrf** [comment]
I like the current box icons and their three-dimensional-ish appearance, so i guess for the `boxes` just two on the ground and one stacked on top and for `box-add` just like `component-add` just with a box.

**Comment by CoreyGinnivan** [comment]
Alright added 🙌  let me know if there's anything else, thanks mate! https://github.com/CoreyGinnivan/system-uicons/pull/48
