### ISSUE TITLE
Precision

### ISSUE THREAD

**Issue by Danny-Engelman** [CoreyGinnivan/system-uicons#8]
````
<svg height="21" viewBox="0 0 21 21" width="21" xmlns="http://www.w3.org/2000/svg">
<path d="m8 13.5172414c4.418278 0 8-3.0259376 8-6.75862071 0-3.73268314-3.581722-6.75862069-8-6.75862069s-8 
3.02593755-8 6.75862069c0 1.45741942.5460328 2.80709561 1.47469581 3.91098161l-.97469581 4.5803977 3.91607376
-2.4472652c1.07810761.4571647 2.29544433.7145066 3.58392624.7145066z" 
fill="none" stroke="#2a2e3b" stroke-linecap="round" stroke-linejoin="round" transform="translate(2 4)"/></svg>
````

With this N.12345678 precision you are stuffing 100,000,000 pixels into 1

**Comment by CoreyGinnivan** [comment]
Thanks mate, will have a look into it 👍

**Comment by dziku86** [comment]
You should run them all through [svgomg](https://github.com/jakearchibald/svgomg). Would be like 40% of the original size for most of your icons.

**Comment by CoreyGinnivan** [comment]
Yeah I've tried doing it few different ways with svgomg, it's almost there but quite a few methods of compression break the icons when imported in to design tools, so just making sure they all still work wherever they're used

**Comment by CoreyGinnivan** [comment]
Fixed up quite a few of them, but will come back to down the line. Closing for now https://github.com/CoreyGinnivan/system-uicons/pull/28
